server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    absolute_redirect off;

    location = / {
        return 302 /gateway-api-visualizer/;
    }

    location = /gateway-api-visualizer {
        return 308 /gateway-api-visualizer/;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /gateway-api-visualizer/404.html;
}
